### ISSUE TITLE
Does not work on rundeck v3.3

### ISSUE THREAD

**Issue by idefixcert** [rundeck-plugins/http-notification#18]
com.dtolabs.rundeck.core.plugins.PluginException: Error loading class: com.rundeck.plugin.HttpNotificationPlugin
	at com.dtolabs.rundeck.core.plugins.JarPluginProviderLoader.loadClass(JarPluginProviderLoader.java:440)
	at com.dtolabs.rundeck.core.plugins.JarPluginProviderLoader.isLoaderFor(JarPluginProviderLoader.java:579)
	at com.dtolabs.rundeck.core.plugins.DirPluginScanner.test(DirPluginScanner.java:220)
	at com.dtolabs.rundeck.core.plugins.DirPluginScanner.scanFor(DirPluginScanner.java:187)
	at com.dtolabs.rundeck.core.plugins.DirPluginScanner.scanForFile(DirPluginScanner.java:140)
	at com.dtolabs.rundeck.core.plugins.FilePluginCache.rescanForItem(FilePluginCache.java:147)
	at com.dtolabs.rundeck.core.plugins.FilePluginCache.getLoaderForIdent(FilePluginCache.java:110)
	at com.dtolabs.rundeck.core.plugins.PluginManagerService.tryPluginMetadata(PluginManagerService.java:199)
	at com.dtolabs.rundeck.core.plugins.PluginManagerService.getPluginMetadata(PluginManagerService.java:189)
	at com.dtolabs.rundeck.core.plugins.ServiceProviderLoader$getPluginMetadata$0.call(Unknown Source)
	at com.dtolabs.rundeck.server.plugins.RundeckPluginRegistry.getPluginMetadata(RundeckPluginRegistry.groovy:801)
	at com.dtolabs.rundeck.core.plugins.PluginRegistry$getPluginMetadata$1.call(Unknown Source)

there is another issue stated:
https://github.com/rundeck/rundeck/issues/6435
It seems that the plugin exects log4j and Rundeck 3.3.X uses log4j2.

I have installed 1.0.5 of the HTTP plugin,

**Comment by fdevans** [comment]
Sorry we missed this.  If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
